version: '2'
services:
  authorizationapplication-app:
    image: authorizationapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://authorizationapplication-postgresql:5432/AuthorizationApplication
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  authorizationapplication-postgresql:
    extends:
      file: postgresql.yml
      service: authorizationapplication-postgresql
